import Head from 'next/head';
import Login from './Login';

export default function Home() {
	return (
		<div className=" w-full md:flex items-center justify-center">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<h1>"hello"</h1>
			</main>
		</div>
	);
}
